name: build

on: 
  push:
    branches:
      - master

jobs:
  linux-cmake:
    strategy:
      matrix:
        target: [linux-arm64, linux-armhf, linux-i686, linux-riscv64, linux-x86_64]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: chrisherb/dpf-cmake-action@main
        with:
          target: ${{ matrix.target }}

  macos-cmake:
    strategy:
      matrix:
        target: [macos-intel, macos-universal]
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: chrisherb/dpf-cmake-action@main
        with:
          target: ${{ matrix.target }}
          macOS_certificate: "${{ secrets.MACOS_CERTIFICATE }}"
          macOS_certificate_pw: "${{ secrets.MACOS_CERTIFICATE_PW }}"

  windows-cmake:
    strategy:
      matrix:
        target: [win32, win64]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: chrisherb/dpf-cmake-action@main
        with:
          target: ${{ matrix.target }}
          pawpaw: true

  pluginval:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: chrisherb/dpf-cmake-action@main
        with:
          target: pluginval
