name: build

on: 
  push:
    branches:
      - master
  workflow_call:
    secrets:
      MACOS_CERTIFICATE:
        required: true
      MACOS_CERTIFICATE_PW:
        required: true

jobs:
  linux-cmake:
    strategy:
      matrix:
        target: [linux-arm64, linux-armhf, linux-i686, linux-riscv64, linux-x86_64]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: chrisherb/dpf-cmake-action@main
        with:
          target: ${{ matrix.target }}
          MACOS_CERTIFICATE: ${{ secrets.MACOS_CERTIFICATE }}
          MACOS_CERTIFICATE_PW: ${{ secrets.MACOS_CERTIFICATE_PW }}

  macos-cmake:
    strategy:
      matrix:
        target: [macos-intel, macos-universal]
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: chrisherb/dpf-cmake-action@main
        with:
          target: ${{ matrix.target }}
          MACOS_CERTIFICATE: ${{ secrets.MACOS_CERTIFICATE }}
          MACOS_CERTIFICATE_PW: ${{ secrets.MACOS_CERTIFICATE_PW }}

  windows-cmake:
    strategy:
      matrix:
        target: [win32, win64]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: chrisherb/dpf-cmake-action@main
        with:
          target: ${{ matrix.target }}
          pawpaw: true
          MACOS_CERTIFICATE: ${{ secrets.MACOS_CERTIFICATE }}
          MACOS_CERTIFICATE_PW: ${{ secrets.MACOS_CERTIFICATE_PW }}

  pluginval:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: chrisherb/dpf-cmake-action@main
        with:
          target: pluginval
